---
- name: Build zz-8
  hosts: all
  tasks:
    - name: Build zz-8 docker image
      shell: docker build -t zz-8 .
      args:
          executable: /bin/bash
          chdir: /home/lance/Src/zz-8
      delegate_to: localhost

    - name: Tag the docker image
      shell: docker tag zz-8 lanceofwhichwedream/home-network:zz-8
      args:
        executable: /bin/bash
        chdir: /home/lance/Src/zz-8
      delegate_to: localhost

    - name: Push the docker image
      shell: docker push lanceofwhichwedream/home-network:zz-8
      args:
        executable: /bin/bash
        chdir: /home/lance/Src/zz-8
      delegate_to: localhost

    - name: git pull the repo
      git:
        repo: git@github.com:lanceofwhichwedream/zz-8.git
        dest: /home/lance/zz-8
        update: yes

    - name: Stop the old docker images
      shell: docker-compose kill
      args:
        executable: /bin/bash
        chdir: /home/lance/zz-8
      ignore_errors: yes

    - name: Pull the new docker images
      shell: docker-compose pull
      args:
        executable: /bin/bash
        chdir: /home/lance/zz-8

    - name: Run da bot
      shell: docker-compose up -d
      args:
        executable: /bin/bash
        chdir: /home/lance/zz-8