---
- name: Install Git and Build Utils
  apt:
    name: ['git', 'build-essential', 'python3-pip', 'python3-virtualenv', 'python3-setuptools']
    state: present

- name: Close the latest code for ZZ-8
  git:
    repo: 'https://github.com/lanceofwhichwedream/zz-8.git'
    dest: /opt/zz-8

- name: Copy the Config file
  template:
    src: templates/config.cfg.j2
    dest: /opt/zz-8/config.cfg

- name: Install the Requirements
  pip:
    requirements: /opt/zz-8/requirements.txt

- name: Create the zz-8 directory
  file:
    path: /etc/service/zz-8
    owner: root
    group: root
    mode: 755
    state: directory

- name: Copy the run script
  copy:
    src: files/run
    dest: /etc/sv/zz-8
    owner: root
    group: root
    mode: 0744

- name: Create ZZ8 Symlink
  file:
    src: /etc/sv/zz-8
    dest: /service/zz-8
    state: link
    owner: root
    group: root

- name: Start ZZ8
  runit:
    name: zz-8
    state: started
